-- The brand board: one image with the logo, the colours, the fonts and a
-- pattern, generated by gpt-image-2.5 together with the logo's recreation.
alter table brand_profiles
  add column board_path text,
  add column board_job_id text,
  add column board_job_status text,
  add column board_error text;
